name: Sync Repos

on:
  schedule:
    - cron: '* * * * *'  # 每天同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repository (your current repo)
      - uses: actions/checkout@v2
        with:
          repository: CyrusZhou-CN/pomelo

      - name: Add and push to target repo
        run: |
          git remote add target https://github.com/NetEase/pomelo.git
          git push target --all
          git push target --tags
